version: 2
jobs:
  coding_standards:
    docker:
      - image: circleci/php:7.2-apache-node-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Composer Packages
          command: composer install
      - run:
          name: Install Node Packages
          command: npm install
      - run:
          name: Install WordPress Coding Standards
          command: vendor/bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs
      - save_cache:
          key: cache-{{ checksum "composer.json" }}-{{ checksum "composer.lock" }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}-{{ checksum ".circleci/config.yml" }}
          paths:
            - vendor
            - node_modules
      - run:
          name: PHPCS Test
          command: composer run lint-php
      - run:
          name: Lint JavaScript
          command: npm run lint-js
      - run:
          name: Lint CSS
          command: npm run lint-css
workflows:
  version: 2
  test_everything:
    jobs:
      - coding_standards
